apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  AccessKeyId: 1gsj9I04zfYlrl6ZdcRKZ42aRWsidjMcJJdPbNcV # AWS access key id (base64 encoded)
  SecretAccessKey: MWdzajlJMDR6Zllscmw2WmRjUktaNDJhUldzaWRqTWNKSmRQYk5jVg== # AWS secret access key (base64 encoded) 
type: Opaque
