# Use envFrom to load Secrets and ConfigMaps into environment variables

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
  labels:
    app: backend-user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user-deployment-app
  template:
    metadata:
      labels:
        app: backend-user-deployment-app
    spec:
      containers:
        - name: udagram-api-user
          image: docker.io/jpetitm/udagram-api-user
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secrets
