# Use envFrom to load Secrets and ConfigMaps into environment variables

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    app: reverseproxy-deployment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy-deployment-app
  template:
    metadata:
      labels:
        app: reverseproxy-deployment-app
    spec:
      containers:
        - name: reverseproxy
          image:docker.io/jpetitm/reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 80
         
